# language: go
# go:
#   - master

dist: xenial
   addons:
     snaps:
       - hugo

sudo: required

# Travis-CI Caching
cache:
  directories:
    - $HOME/gopath/pkg/mod
    - $HOME/.cache/go-build
    - $HOME/Library/Caches/go-build
    - $HOME/AppData/Local/go-build


# S: Build Lifecycle
# install:
#   - sudo apt-get update
#   - sudo apt-get -y install hugo

before_script:
  - rm -rf public 2> /dev/null

script:
  - hugo version
  - hugo

after_script:
  - cd public
  - git init
  - git config user.name "${GITHUB_USERNAME}"
  - git config user.email "${GITHUB_EMAIL}"
  - git add .
  - git commit -m "Update Blog"
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/JMwill/blog.git
   # - secure: "d1OAv1FuqKvuVL0PCghc6BScff4Gs+WXSQnha/n2QgrT3lq1TngvF8Z4YfRK3UpxRIftdNJRFeLebtX7l90u1dj0M3vc6nWr5w//xIB2j7jPLI7PdareMaGM0AOOBXkLjuvuQtp6114BnCQqX6hIa3vDYfYsXJ+hqC4MoAGWe3umL/AfOit2TwbNgWksxzXcpTdhHiJD5dHO71MsZicLCuWkH94Qr8U69CK/Go672c8zC4Z6O11H6f/vw9g0cZP9p4lKMzDKKH4RohH3WXPSu7jdFXSn66rRiqhLTLd9eq8mRCswIZ5xlddoc3k5PB3X2Z+yvYe3cCy94G883EodONYUzSuMsS6UyxaAofMPm9BY6FR+4lpAkmyMRQq695cdz7DPXk+u6OW2EtquJkQHwcW6v2y4AWX6jToY+cYcj0YvFO3gOYIeKvSE8heh5RLo0rYTT2YCb5zgTYv0DiCGnfFQGF/0iyQJ5HWjULzhRd/nwxEtbxkaHFcRrA6Pl+VPfz+ytoLpUXhErIrp7HYfjBtj98XF0XAsIKyTIUVaLAYxs0J7ujU9/JxOmvl3XBEU1V7VVcUJ/n89w3sRQv93RKryWh8kKsO3fZdKBjZkUqs3wca4B7BdEF1NZWE+05Zf5iWzyrHbxsMtdzbHUoSbu14Ziv1SSLTu0RXyzLHAKAo="