language: node_js
node_js: stable

sudo: false

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install hexo-cli -g
  - npm install
  - npm install hexo-generator-sitemap --save
  - npm install hexo-generator-baidu-sitemap --save

#before_script:
#  - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd public
  - git init
  - git config user.name "JMwill"
  - git config user.email "787505998@qq.com"
  - git add .
  - git commit -m "Update Blog"
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/JMwill/blog.git
   - secure: "Mmu/gMLGuunR6pzxvlAzu/nQqYbxQoOEH/M1u2fUxyLq8+sEWdNyVF2NYODw5i4GASgabG5Ylju7eb1Qv1ShsSC4Drve4AHESyZkvEX3pBAKkzi5kgnSZmaWgEMAFawr1ltnuYJkbDZipPibQWAY58kcdfrkPdAlc83tln059DXmnldbiOV4rfNe1/IIDYVnjCC6ZDd+LI0kc7nNy61b4XdqXqAMJ8GsAcT5XOvHTYd+Lv6w3A283gnJxIDaqkcChfnx33uDITKyNXuqUIBRZbzg/W97GXlxX9MHd+rCruEv+3fl2VW/aXivWa/bnfq6RUVKLuYsV0bBjkwIkWoOwRgx0UNMJaaFq5xTKhQvQnB5q1/td41VBhZz3QR2LF4ORdM0WjR1nBLj0igWh9knDSkNnx58ywB+4xfoqYRNOdB4yezjwxsnNNmYX9xeiq/KBZYx8ngo8Y/dCZMAh67SeYYw9B3y+yRc5ijDk3U/U3ngjDnrYhWLjNtaJ7gC2s6Q+rfZSBxRlkj5vMJkjcVKebaBWgvQexRrxCoVnoyNFFvUwDrBOpImQvie79rEeSt7VVs93xYCHzipkHS7gBlUcBSEyY7tttDhiGduf8/WHhgNnwhNGgo8iiQAYj2ossxEHlNrpAMKP3MDiHaQ3y4i4tTN2+kSAO7hSWu1Jk3hViA="